### ISSUE TITLE
Instructions on how to use

### ISSUE THREAD

**Issue by kishore-narendran** [joelbandi/Be-ethoven#2]
Consider, writing something in the README.md, for people who want to see how your project works. Possibly with examples on how to use this java project. 

I am assuming this project, is about parsing text in some manner to create music?

**Comment by joelbandi** [comment]
Ah. Thanks for reminding. This repo needs a cleanup and a .gitignore file. This project tracks your hand movement using LeapMotion sensor arrays and translates your movement into tones of different frequency and octaves, just like an orchestra conductor would

**Comment by kishore-narendran** [comment]
Interesting! You should put up details. Good stuff. 👍

**Comment by joelbandi** [comment]
Thanks mate!

**Comment by joelbandi** [comment]
Hey! I fixed it . Thanks again. :smile:
